vich_uploader:
    db_driver: orm

    mappings:
        activite_images:
            uri_prefix:         '%app.path.activite_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.activite_images%'